language: python

python:
  - "3.5"

addons:
  apt:
    packages:
    - libkeyutils-dev
# NOTE: Travis currently runs tests on Ubuntu 14.04 (trusty) whose native
# python3 distribution is py34. This means that we do not have access to
# adequate system packages for use with `--system-site-packages`:
#   - python-gobject
#   - python3-gi
# virtualenv:
#   system_site_packages: true

install:
  - pip install keyutils
  - python setup.py sdist
  - pip install $(ls ./dist/*.tar.gz | sort -rV | head -n1)
  - pip install flake8

script:
  - flake8
  - nosetests
