language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"
install:
  - sudo apt-get -qy update
  - sudo apt-get -qy install zenity libdbus-1-dev libdbus-glib-1-dev
  - PREFIX=$VIRTUAL_ENV ./build_requirements.sh
  - python setup.py sdist
  - pip install $(ls ./dist/*.tar.gz | sort -rV | head -n1)
script:
  - nosetests
