language: python

# Restrict testing to system native python versions.
# This means that binary distributions can be used for the dependencies.
# Travis runs on Ubuntu 12.04 LTS currently. :(
python:
  - "2.7"
  - "3.4"       # trusty's native python3 version

addons:
  apt:
    packages:
    - python-gobject
    - python3-gi
    - libkeyutils-dev

virtualenv:
  system_site_packages: true

install:
  - pip install keyutils
  - python setup.py sdist
  - pip install $(ls ./dist/*.tar.gz | sort -rV | head -n1)

script:
  - nosetests
